change integration to check documentation, test, jsdoc

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -4,6 +4,9 @@ on:
   pull_request:
     branches:
       - develop
+  push:
+    branches:
+      - fix/integration
 
 jobs:
   lint:
@@ -41,11 +44,15 @@ jobs:
         id: filter
         uses: dorny/paths-filter@v3
         with:
-          list-files: csv
+          list-files: shell
           filters: |
             changed:
-              - 'src/**/*.ts'
-              - 'src/**/*.tsx'
+              - 'src/components/**/*.ts'
+              - 'src/components/**/*.tsx'
+              - 'src/hooks/**/*.ts'
+              - 'src/hooks/**/*.tsx'
+              - 'src/utils/**/*.ts'
+              - 'src/utils/**/*.tsx'
 
   verify-documentation:
     runs-on: ubuntu-latest
@@ -57,18 +64,14 @@ jobs:
 
       - name: Verify documentation exists
         run: |
-          for file in $(echo "${{ needs.check-changes.outputs.changed_files }}" | tr ',' '\n'); do
-            if [[ "$file" != *.ts && "$file" != *.tsx ]]; then
-              continue
-            fi
+          for file in ${{ needs.check-changes.outputs.changed_files }}; do
             dir_name=$(basename $(dirname "$file"))
-            base_name=$(basename "${file%.*}")
-            if [ "$dir_name" != "$base_name" ]; then
-              continue
-            fi
+            base_name=$(basename $dir_name)
+
             doc_file="$(dirname "$file")/$base_name.md"
+            
             if [ ! -f "$doc_file" ]; then
-              echo "Documentation missing for $file"
+              echo "Documentation missing for $base_name"
               exit 1
             fi
           done
@@ -91,24 +94,20 @@ jobs:
           corepack enable
           yarn install
 
-          for file in $(echo "${{ needs.check-changes.outputs.changed_files }}" | tr ',' '\n'); do
-            if [[ "$file" != *.ts && "$file" != *.tsx ]]; then
-              continue
-            fi
+          for file in ${{ needs.check-changes.outputs.changed_files }}; do
             dir_name=$(basename $(dirname "$file"))
-            base_name=$(basename "${file%.*}")
-            if [ "$dir_name" != "$base_name" ]; then
-              continue
-            fi
+            base_name=$(basename $dir_name)
+
             test_file="$(dirname "$file")/$base_name.spec.ts"
+
             if [ ! -f "$test_file" ]; then
               test_file="$(dirname "$file")/$base_name.spec.tsx"
+
               if [ ! -f "$test_file" ]; then
-                echo "Test file missing for $file"
+                echo "Test file missing for $base_name"
                 exit 1
               fi
             fi
-            yarn run test:coverage $test_file
           done
 
   verify-jsdoc:
@@ -121,17 +120,22 @@ jobs:
 
       - name: Check for JSDoc comments
         run: |
-          for file in $(echo "${{ needs.check-changes.outputs.changed_files }}" | tr ',' '\n'); do
-            if [[ "$file" != *.ts && "$file" != *.tsx ]]; then
-              continue
-            fi
+          for file in ${{ needs.check-changes.outputs.changed_files }}; do
             dir_name=$(basename $(dirname "$file"))
-            base_name=$(basename "${file%.*}")
-            if [ "$dir_name" != "$base_name" ]; then
-              continue
+            base_name=$(basename $dir_name)
+            implementation="$(dirname "$file")/$base_name.ts"
+
+            if [ ! -f "$implementation" ]; then
+              implementation="$(dirname "$file")/$base_name.tsx"
+
+              if [ ! -f "$implementation" ]; then
+                echo "Implementation missing for $file"
+                exit 1
+              fi
             fi
-            if ! grep -q "/**" "$file"; then
-              echo "JSDoc comments missing in $file"
+
+            if ! grep -q "/\*\*" "$implementation"; then
+              echo "JSDoc comments missing in $implementation"
               exit 1
             fi
           done
