change `verify-test` job to check test coverage 100%

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -89,15 +89,27 @@ jobs:
         with:
           node-version: '20.x'
 
-      - name: Verify and run tests with coverage
+      - name: Install dependencies
         run: |
           corepack enable
           yarn install
 
-          for file in ${{ needs.check-changes.outputs.changed_files }}; do
+      - name: Run tests and generate coverage
+        run: yarn run test:coverage
+
+      - name: Verify test coverage
+        run: |
+          changed_files="${{ needs.check-changes.outputs.changed_files }}"
+          coverage_file="coverage/coverage-final.json"
+
+          if [ ! -f "$coverage_file" ]; then
+            echo "Coverage file not found!"
+            exit 1
+          fi
+
+          for file in $changed_files; do
             dir_name=$(basename $(dirname "$file"))
             base_name=$(basename $dir_name)
-
             test_file="$(dirname "$file")/$base_name.spec.ts"
 
             if [ ! -f "$test_file" ]; then
@@ -107,6 +119,36 @@ jobs:
                 echo "Test file missing for $base_name"
                 exit 1
               fi
+            fi
+
+            # Debugging: Print the file path
+            echo "Checking coverage for: $file"
+
+            # Calculate coverage percentage for each matching entry
+            total_lines=0
+            covered_lines=0
+
+            # Iterate over each matching coverage data entry
+            for entry in $(jq -c --arg base_name "$base_name" '. | to_entries[] | select(.key | contains($base_name)) | .value' "$coverage_file"); do
+              entry_total_lines=$(echo "$entry" | jq '.s | length')
+              entry_covered_lines=$(echo "$entry" | jq '[.s[] | select(. > 0)] | length')
+
+              # Accumulate total and covered lines
+              total_lines=$((total_lines + entry_total_lines))
+              covered_lines=$((covered_lines + entry_covered_lines))
+            done
+
+            # Calculate overall coverage percentage
+            coverage=$(echo "scale=2; ($covered_lines / $total_lines) * 100" | bc)
+
+            # Debugging: Print accumulated total and covered lines
+            echo "Total lines: $total_lines, Covered lines: $covered_lines"
+            echo "Coverage: $coverage%"
+
+            # Correct the condition to check if coverage is less than 100
+            if (( $(echo "$coverage < 100" | bc -l) )); then
+              echo "Test coverage for $base_name is not 100%: $coverage%"
+              exit 1
             fi
           done
 
